### ISSUE TITLE
HTML tags & params in the translation files

### ISSUE THREAD

**Issue by igor-h** [while1618/i18n-auto-translation#11]
Hi, 
I have a issue using:  **azure-official** with the following command line: 

`i18n-auto-translation --apiProvider azure-official --key <my-api-secrey-key> --region westeurope --from en --to zh-Hans --dirPath src/main/webapp/i18n --override true`

I have some HTML tags and parameters in my translations like: 
`<strong> <br /> <ul> <li> <p>` and translation parameters: `{{param1}} {{param2}}` in some languages they're well translated but in some other randomly half of the labels are translated. 

> ### Examples: 
**Original text:**
`    "form.return-by-app": "This form was <strong>Returned by data app</strong> with the following comments:",`

after the translations, for example in chinesse: looks like this:
`    "form.return-by-app": "此表单由万事达数据</强><强>返回，并附有以下评论：",`
in **Chinesse** both html tags `<strong> `& `</strong>`  are translated to chinesse directly: `<强> </强>`

Result in **Spanish** only one HTML tag were translated:
`    "form.return-by-app": "Este formulario fue <fuerte>Returned por applicación de datos</strong> con los siguientes comentarios:",`

but in spanish only the first `<strong>` is translated like `<fuerte>`

> ### Second example but with parameters:

**English translation:**
`"global.item-count": "Showing {{first}} - {{second}} of {{total}} items.",`

**Spanish:** (correct result as expected) 👍🏽 
`"global.item-count": "Mostrando {{first}} - {{second}} de {{total}} elementos.",`

**Chinesse:** param names are lost 👎🏽 
`"global.item-count": "显示 {{第一}} - {{总计}} 项的 {{第二}} 项。",`

Is this issue related to @microsoft Azure Translation API?

Thanks!
Igor.

**Comment by while1618** [comment]
Yea, I think this is on them. 

If you have, for example, something like this in your sentence "{{test}}", I'll send that to the translation API. Google API will recognize that as something they shouldn't translate, but Azure apparently will not.

I can maybe remove words from a sentence with some special characters like {{}} or <>, then send a request, and map back the removed words, but that will take time, which I currently do not have. 

If you have some time to work on it, I'll gladly accept PR. If not, maybe in some near future, I'll try to implement it.

You can also open an issue on Azure API, and check if they can fix it, or try to use Google API if that's an option.

**Comment by igor-h** [comment]
I'll create a pull request for this change then 👍🏽  we stay in touch! 
Thanks  @while1618  for having create the project!

**Comment by while1618** [comment]
Hi @igor-h,

This is now resolved. It will work as expected from version `1.2.8`, you can check #19 for additional information.

**Comment by igor-h** [comment]
Hi @while1618 
Thanks!!
