### ISSUE TITLE
Strange Trouble

### ISSUE THREAD

**Issue by breakiboy** [while1618/i18n-auto-translation#12]
HI, firstly thank you for sharing this project with us. Really interesting project. I tryed today this tool and got some strange results. Here is one Example:

 "card1": "我们的金件{ |} 观看次数最多",    If I got { |}  <- all values are moved up one position. And in my file I have alot of this { |}. I tryed with some other source target files but same result.

**Comment by while1618** [comment]
Hi @breakiboy, "{|}" is my delimiter, for some reason, in some requests my delimiter might return as "{ |}" and that's what is causing a problem. I thought that I fixed that by changing the delimiter, but apparently I was wrong. I'll try to resolve it with a different approach. Can you provide me the API you used and json file you wanted to translate?

**Comment by ETCasual** [comment]
@while1618 im having this issue as well, im using `google-official`, and translating to `zh-CN` too, similar to OP. `{ |}` shifts the translation upwards.

**Comment by while1618** [comment]
@ETCasual can you give me the original json file you wanted to translate? I'll reproduce the error and i'll try to fix it

**Comment by ETCasual** [comment]
@while1618 where can i send it to you?

**Comment by while1618** [comment]
@ETCasual just paste the problematic snippet here

**Comment by ETCasual** [comment]
The file is pretty big, can i send u via email?

**Comment by while1618** [comment]
I don't need the whole file, just from the beggining, until the first line that is not translated well. If it's still to big, you have email address on my github profile, so you can send me the file

**Comment by while1618** [comment]
Hi @ETCasual, @breakiboy, can you update package to v1.1.16 and check if the problem is resolved now?

**Comment by ETCasual** [comment]
![image](https://user-images.githubusercontent.com/68994115/198916084-2b77b3ae-132f-46e2-954a-0f09dc4f4ae6.png)
It seems that it still errors out

**Comment by while1618** [comment]
Oh, so it can also be '{| }', i thought that only '{ |}' can happend.

I'll add both cases and let you know when v1.1.17 is out.

**Comment by ETCasual** [comment]
thanks bro @while1618 , really appreciate the work you do!

**Comment by while1618** [comment]
@ETCasual can you try with v1.1.17?

**Comment by ETCasual** [comment]
@while1618 much better, the delimiters are not in the file anymore, however some lines are still shifted, for example 
![image](https://user-images.githubusercontent.com/68994115/199201092-ae9c8afd-c8bf-425f-b71a-8e2cf0718dc6.png)

The red cross means the translation is totally wrong, 
the yellow arrow means the translations have shifted downwards

**Comment by while1618** [comment]
Did you override the file or just append it? Just appending might be a problem, because of previous wrong translations

**Comment by ETCasual** [comment]
i always delete the translated file before running another translation. So it shouldnt be a problem

**Comment by while1618** [comment]
I'm really not sure what can be a problem here. I currently do not have the key for the google translate, but I'll try to test it with some other provider during the weekend.

Maybe it's just too large file for the API to return meaningful results, you can try to split that into 3-4 smaller files and then try to translate it.

**Comment by dippyshere** [comment]
Hi, when translating [this file](https://github.com/dippyshere/stw-daily/blob/mango/lang/en.json), I encountered this same issue, with some languages being offset/shifted *many* times (~1-16 lines). I was using `google-official`, and found these languages to be problematic: `ro, ja, hi, es-ES, el, cs, te, ta, sw, sk, pa, ur, mr, lv, lt, he, ha, gu, fi, fa, et, ca, bn, tr, no, zh-CHS, zh-CHT`. 

I found `af, ar, bg, da, de, fr, hr, hu, id, it, ko, ms, nl, pl, pt-BR, ru, sr, sv-SE, th, uk, vi` to work pretty well, with only minor issues (caused by Google Translate, not this project)

Your suggestion of splitting the large file into smaller chunks worked perfectly for those problematic languages. I split the file into 5 chunks, translated, and assembled it back with no issues.

**Comment by Snargol** [comment]
Same problem here, the solution of splitting into several small files is not practical but works well.

Thanks for your work, which has saved me a lot of time, even with the bug.

**Comment by while1618** [comment]
I'll try to fix this by sending max 200 lines to translate provider, if the file have more than 200 lines, I'll just split into multiple requests, and then map back everything to one file. So after that, you will no longer need to do splitting manually.

Until then, there is at least this manual solution that will work.

**Comment by while1618** [comment]
Hi @dippyshere, @Snargol,

`v1.3.0` of library is published, and now it will automatically split the file into 200 lines per request if necessary, and then map them to one file as expected.

I tested this on the file @dippyshere provided, and for me, it worked correctly. I translated the file to `ja` with `deep-rapid` (it uses the same api as google, but I don't have google api key right now to test with it), if some of you can test it just as confirmation that it is working correctly now I would be grateful.

The solution is implemented in a way that api provider doesn't matter, but just to be sure.
