### ISSUE TITLE
replaceAll is not a function

### ISSUE THREAD

**Issue by bwiklund** [while1618/i18n-auto-translation#16]
Just a small bug I found: `replaceAll` is not present in node < 15. You may wanna use an older method, or just mark the package as incompatable with node < 15. Thanks for this super helpful project!

```
Request error for file: Data\locales\en.json
TypeError: value.replaceAll is not a function
    at GoogleOfficialAPI.Translate.saveTranslation ([...]\.nvm\versions\node\v14.20.0\bin\node_modules\i18n-auto-translation\dist\translate\translate.js:92:18)
    at [...]\.nvm\versions\node\v14.20.0\bin\node_modules\i18n-auto-translation\dist\translate\providers\google-official-api.js:19:22
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by while1618** [comment]
Hi @bwiklund, I forgot that replaceAll method won't work on node < 15. I just replace it with my custom replaceAll, now v1.1.20 of my lib should be compatible with node < 15.

Thanks for the update, let me know if you find anything else, or still face some issue with this problem.

**Comment by bwiklund** [comment]
great, thanks!
