### ISSUE TITLE
Feature Request on empty strings

### ISSUE THREAD

**Issue by alexnoise79** [while1618/i18n-auto-translation#17]
This plugin is amazing and very helpful

this is a Feature request for a new option to check IF there are empty translations to be filled, or ignore translated ones.

all the missing translated strings "", will be populated, other ones ignored.

this is helpful when translations are being modified and some sections are missing.

**Comment by while1618** [comment]
Hi @alexnoise79, if I understood your request right, this is already implemented.

You can check demo section in README, and see how it works.

**Comment by alexnoise79** [comment]
Hi @while1618 

yes i saw it but this is working only IF the key is not available, but in real life when you use other plugins to extract translation, the json file has the keys, but the values are "" empty strings.

in that case your plugin is not working.

(plus, translations are always inserted at the end of the file, usually they are sorted alphabetically)

mine are just suggestions, would appreciate if they are taken into consideration :)
