### ISSUE TITLE
yaml file first line language key and recognition of existing already translated lines

### ISSUE THREAD

**Issue by kgorshkov** [while1618/i18n-auto-translation#24]
For yaml files, the first line is the language code, such as 'en:'

```
en:
  hello: "Hello world"
```

The translation to another language such as 'es' creates a new file es.yml where the first line language code is still 'en:'

```
en:
  hello: "Hola Mundo"
```

It would be good if i18n-auto-translation would recognize the first line language code and update it as part of the output translated language file.

The issue is the when the first line language code is updated manually, i18n-auto-translation no longer recognizes that all following sub or indented keys and their translations are existing already-translated lines if i18n-auto-translation is run again for updates:

Example:

First run: 

> Invoke 'google-translate' from 'en' to 'es' with 1 inputs...
> Add 1 new translations
> Write target 'C:\Users\KG\app\config\locales\es-test.yml'

Manually edit first line language code to es:

```
es:
  hello: "Hola Mundo"

```

Expected on second run with edited existing file es-test.yml:

> Target is up-to-date: '.\config\locales\es-test.yml'

Actual: 

> Invoke 'google-translate' from 'en' to 'es' with 1 inputs...
> Add 1 new translations
> Delete 1 stale translations
> Write target 'C:\Users\KG\cartinsights\config\locales\es-test.yml'

Please advise how I can handle yaml file updates, thanks.

**Comment by while1618** [comment]
hi @kgorshkov,

yaml files are not supported at all, only json files. I'm really surprised that anything works with yaml.

Maybe in some near future I can support yaml files, but for now you can only use this library with json.

If I ever create support for yaml, I'll let you know here in this issue, but for now I don't have time to do that.

**Comment by kgorshkov** [comment]
Apologies I posted this in the incorrect git project.
