### ISSUE TITLE
Azure AI Translator

### ISSUE THREAD

**Issue by JarJarBinks91** [while1618/i18n-auto-translation#25]
Is it possible to use your package with the Azure AI Translator? If so, do you have an example?

https://learn.microsoft.com/en-us/azure/ai-services/translator/

**Comment by while1618** [comment]
Hi @JarJarBinks91,

Yes, that will be `azure-official` in my project.

In order to use it, you just need to pass `apiProvider` parameter like so:

```
$ i18n-auto-translation -k SUBSCRIPTION_KEY -d PROJECT_DIR -t DESIRED_LANGUAGE -a azure-official
```
