### ISSUE TITLE
Published version 1.2.12 is outdated

### ISSUE THREAD

**Issue by Datawalke** [while1618/i18n-auto-translation#26]
Hi,

It looks like the `/dist` directory in the NPM package for the latest build is incorrect
![image](https://github.com/while1618/i18n-auto-translation/assets/383511/2e030e60-0342-4f47-bd04-5cfd115666c9)

The CLI is missing `choices` for apiProviders. (deepl-free, deepl-pro)

I just wanted to give you a heads up! Downloading the project and compiling from source works as expected with all providers showing.

Thank you for your time and effort!

**Comment by while1618** [comment]
Hi @Datawalke,

I forgot to run `npm run build` 🤦‍♂️

I definitely need to publish this via GitHub Actions... 

Thanks for pointing this out, I'll fix it immediately.

**Comment by while1618** [comment]
Fixed in `v1.2.13`

**Comment by Datawalke** [comment]
You are awesome!
