### ISSUE TITLE
translate too many times

### ISSUE THREAD

**Issue by Snargol** [while1618/i18n-auto-translation#27]
I used the tool for a while without any problems.
Then it stopped working. So I did a test with a very small file (just one line).

My command: i18n-auto-translation -a deepl-pro -k [MY_KEY] -d . -f fr -t nl

Finding files for translation...
15 files found.
File saved: nl.json
Request error for file: fr.json
Request failed with status code 456
Request error for file: fr.json
Request failed with status code 456
File updated: nl.json
File updated: nl.json
File updated: nl.json
File updated: nl.json
File updated: nl.json
File updated: nl.json
File updated: nl.json
File updated: nl.json
File updated: nl.json
File updated: nl.json
File updated: nl.json
File updated: nl.json

it didn't work, but it also made me use 800,000 characters on deepl pro ... (because I set a maximum amount, otherwise it would have continued I think, since I've reached the maximum).
I only have one nl.json file, the 15 files correspond to the 15 languages I have

edit: it's my fault because I launched it out of the directory. a security system would still be a very good thing ... 😅

**Comment by while1618** [comment]
I'll add some confirmation message just to be sure where are you running the script and which files will be affected.
