### ISSUE TITLE
Azure official API doesn't split properly when returning values due to a space in the "sentence delimiter"

### ISSUE THREAD

**Issue by msnyder-msft** [while1618/i18n-auto-translation#3]
For some reason, when the string comes back from the Azure-official API has a space in the delimiter ("| *|" instead of "|*|"). This means that when it tries to do the split in `saveTranslations` the split doesn't line up with the original object and all the translations end up on the wrong keys. 

Partial sample input: 
 [{"text":"Loading...|*|Hierarchy|*|Display name|*|Real-time status|*|Empty composite card|*|Composite card with error boundaries|*|Show more|*|Access Restricted|*|You do not have access to this blob. Request Reader access or try a different blob.|*|Blob Error|*|Blob does not exist.|*|You have read access for this blob. This means that you will be able to view the models, but will not be able to create or configure any scenes, elements, or behaviors."}]

Partial result: 
Cargando...| *| Jerarquía|*| Nombre para mostrar|*| Estado en tiempo real|*| Tarjeta compuesta vacía|*| Tarjeta compuesta con límites de error|*| Mostrar más|*| Acceso restringido|*| No tiene acceso a este blob. Solicite acceso al lector o pruebe con otro blob.**| *|** Error de blob|*| Blob no existe.| *| Tiene acceso de lectura para este blob. Esto significa que podrá ver los modelos, pero no podrá crear ni configurar escenas, elementos o comportamientos.| *| Inténtalo de nuevo|*| Más información|*| Error en la captura de datos|*| Más|*| Buscar|*| No se han encontrado gemelos para el término de búsqueda introducido (la búsqueda distingue entre mayúsculas y minúsculas).| *| Modelo|*| Sin gemelos|*| Sin modelos|*| Verdadero|*| Falso|*| Activado|*| Desactivado|*| Ajustar texto|*| Copia|*| Copiado|*| Cerrar|*| Volver|*| Anterior|*| Siguiente|*| Propiedades|*|blank|*| Nuevo|*| Ver|*| Construir|*| Descargar|*| Url|*| Crear|*| Guardar|*| Añadir|*| Añadir nuevo|*| Eliminar|*| Actualización|*| Cancelar|*| Borrar|*| Editar|*| Conectar|*| Editar gemelo|*| Confirmar eliminación|*| ¿Estás seguro? No se puede deshacer esta acción.| *| Acción|*| Nombre|*| Título|*| Introduzca el título|*| Creador de tarjetas de gráfico de líneas|*| No se proporciona información|*| No disponible|*| Tamaño|*| Subir|*|o|*| Tipo|*| Id|*| Seleccionar|*| Información|*| Instancias de Azure Digital Twins|*| Lista de instancias de ADT para las que el usuario tiene permiso de Azure Digital Twins Data Owner o Azure Digital Twins Data Reader|*| Cargando instancias...**| *|**

**Comment by msnyder-msft** [comment]
I found that doing something like this helps to resolve the issue (if you can figure out how to use `replaceAll` directly that would be cleaner but this was just me figuring out the issue. 
![image](https://user-images.githubusercontent.com/57726991/163021563-77c05567-5979-42da-8589-21abc94e7da4.png)

**Comment by while1618** [comment]
Fixed in v1.1.10
