### ISSUE TITLE
Weird bug when translating files

### ISSUE THREAD

**Issue by Yohannfra** [while1618/i18n-auto-translation#39]
Hi,

First let me thank you for this tool this will save me so much time.

I just tried it and I have this weird bug with the translation I don't know where it could come from.

So I have this **fr.json**

```json
{
  "Admin": {
    "Sidebar": {
      "actions": "Actions",
      "api_usages": "Utilisations API",
      "disconnect": "Se déconnecter",
      "establishments": "Établissements",
      "playground": "Expérimentations",
      "users": "Utilisateurs"
    }
  }
}
```

And I want to create the italian tranlsation file from it. So I run 

```bash
i18n-auto-translation        \
    -d ./messages/        \
    --from fr                \
    --to it                  \
    --apiProvider deepl-free \
    --key $DEEPL_API_SECRET_KEY
```

And the created **it.json** looks like this

```json
{
  "Admin": {
    "Sidebar": {
      "actions": "Azioni",
      "api_usages": "API utilizza",
      "disconnect": "Disconnettersi\n\nStabilimenti\n\nEsperimenti",
      "establishments": "Utenti"
    }
  }
}
```

It looks like there is a bug where this create '\n' in the values and don't create new values after the **disconnect**.

Thank you,

Yohann

**Comment by while1618** [comment]
Hi,

I sadly do not have api key for deepl translate right now, but I tried your `fr.json` with other apis and it worked as expected. I even added `\n\n` in json just to check will that break anything, but still, it worked fine.

It might be that the response from deepl is not correct for some reason, but I can't check that without the key.

Can you try some other translate provider?

Alternatively, we can check this together on some discord call with your key and try to debug it, or you could build this project and run it locally, just add some logs in `callTranslateAPI` inside `deepl-free-api.ts`. I'm here if you need any help, but can't do much without the key.

**Comment by Yohannfra** [comment]
<img width="1274" alt="Capture d’écran 2024-04-15 à 01 18 38" src="https://github.com/while1618/i18n-auto-translation/assets/36271388/0e886094-b3cb-4442-a2af-ebf6f2a1cce8">

This is what I get with a 
```js 
console.log(valuesForTranslation)
```

and after a 

```js
console.log((response as DeepLTranslateResponse).data.translations[0].text)
```

---

It doesn't help me much finding the issue, it looks like the deepl api doesn't like the **Translate.sentenceDelimiter** .

For now since I really need this to work asap I made a dirty fix by calling axios in a loop with values one by one. It's slower but works well for me so I can use this fork for some time until we find a solution.

This is the modification I made:

```ts
  protected callTranslateAPI = async (valuesForTranslation: string[]): Promise<string> => {
    const res = [];
    for (const v of valuesForTranslation) {
      const response = await axios.post(
        `https://${DeepLFreeAPI.endpoint}/v2/translate`,
        {
          text: [encode(v)],
          target_lang: argv.to,
          source_lang: argv.from,
          preserve_formatting: true,
        },
        DeepLFreeAPI.axiosConfig,
      );
      res.push(decode((response as DeepLTranslateResponse).data.translations[0].text));
    }
    return res.join(Translate.sentenceDelimiter);
  };
}
```

Thank you for guiding me and if you want more logs or that I run some test with my deepl key feel free to ask.

Yohann

**Comment by while1618** [comment]
Have you tried to change `Translate.sentenceDelimiter`? It's declared in `translate.ts`, and you only need to change it there. For your end result, it makes sense to be like that if the delimiter is deleted, it will not know where to split words, and it will just put them in one line. Also, have you test it with other json structure? I assume it will happen again, but just to be sure.

It seems to me that the problem is deepl api response, maybe we will have some luck with changing delimiter

**Comment by while1618** [comment]
Hi @Yohannfra,

I finally got deepl key, and tested json you provided. It was the same issue for me, so I changed the delimiter, and the problem is resolved now.

Version `1.5.0` have a fix, so if you are still using this, just update the library, and it should work as expected, no need for modification on your side.
