### ISSUE TITLE
Some strings come back with a space appended at the start?

### ISSUE THREAD

**Issue by msnyder-msft** [while1618/i18n-auto-translation#4]
I have noticed that some of my strings (but not all) come back with a space at the start. I'm not sure if it's specific to the Azure-official API or not. 
You can see that Model doesn't have the space, but most of the rest do.
![image](https://user-images.githubusercontent.com/57726991/163021812-0d4c1127-ca6f-4cd6-aef6-bc6bc30065b3.png)

**Comment by while1618** [comment]
Fixed in v1.1.10
