### ISSUE TITLE
Translation lines shifting and some translations missing

### ISSUE THREAD

**Issue by Andrew-Tierno** [while1618/i18n-auto-translation#46]
Hi! First of all, love your project. I'm running into an issue that is potentially related to #12.

I have a large(ish) file of ~500 lines that I'm running through your script with google-official. Specifically running:
```bash
i18n-auto-translation -k $SECRET_KEY --from en --to hi --filePath en.json
```

My translation files (attached shortened versions below) are formatted like
```json
{
  "like": {
    "header": "A header about the like section."
    "001": "The first like quote",
    "002": "The second like quote",
    "...": "...",
    "250": "The last like quote"
  }
  "recommend": {
    "header": "The recommend header.",
    "001": "The first recommend quote",
    "002": "The second recommend quote",
    "...": "...",
    "250": "The last recommend quote"
}
```
but after running through the script, some keys in the translated file are jumbled and some are completely missing, leaving something like:

```json
{
  "like": {
    "header": "The second like quote"
    "001": "The first like quote",
    "002": "A header about the like section.",
    "...": "...",
    "250": ""
  }
  "recommend": {
    "header": "The second recommend quote",
    "001": "",
    "002": "The recommend header.",
    "...": "...",
    "250": "The last recommend quote"
}
```
Fortunately (and for whatever reason), the translations do not swap between containing dictionaries ("like" and "recommend" stay separate). I have attached the `hi` translation, but this issue also occurs (weirdly, at different thresholds of quotes for different languages) in `es`, `fr`, `zh`, and `ar` as well. 

I saw this may be related to the Google Translate API (though even with the attached files which have fewer than 200 lines this issue seems to occur). 

Would love any guidance on this!

[en.json](https://github.com/user-attachments/files/16645451/quotes.json)
[hi.json](https://github.com/user-attachments/files/16645453/quotes.json)

**Comment by while1618** [comment]
Hi @Andrew-Tierno,

Sadly, I don't have Google api key anymore, so couldn't test with it.
But I test it with `azure` and `deepl`, and both worked correctly for `sr`, `de` and `hi`.

So I would assume that this is related with how google gives back those translations, maybe you can try to divide this file in 3-4 smaller files and try again. Or if you are able, try to switch translate provider.

**Comment by Andrew-Tierno** [comment]
Hi @while1618, thanks for the quick reply. I'd be happy to grant you an API key on a sample project if you'd be willing to take a look. If not, I'll try one of the interventions you suggested and report back.

**Comment by while1618** [comment]
I'll gladly check on this. You can send me the key on `dejan.zdravkovic@protonmail.com`. Promise I won't abuse it in any way, I'll just run a couple of tests with your provided file.

I'll probably check on this tomorrow/day after tomorrow, and will let you know once it's done, so you can revoke your key.

**Comment by Andrew-Tierno** [comment]
Unfortunately it seems that Google wants you to have a Google Account to access GCP resources (I'm a protomail user too I find this very frustrating). Would you mind sending one over?

**Comment by while1618** [comment]
`dejan.zdravkovic96@gmail.com`

**Comment by Andrew-Tierno** [comment]
Added! There is a key called `Translation Key` accessible from `APIs & Services > Credentials`. Let me know if you have any permission issues.

**Comment by while1618** [comment]
I have a permission problem, can you write me an email, so that I can share with you what the error is?

**Comment by Andrew-Tierno** [comment]
Sent to your protonmail account

**Comment by while1618** [comment]
Hey @Andrew-Tierno,

Just finished checking on this. It's definitely google response that is a problem here, on some languages it will work as expected, it worked with `sr` and `de`, but `hi` was problematic. Also, it's related to #12 as you mentioned. 

I solved #12 by putting `maxLinesPerRequest = 200`, that will split the file if it's larger than `200` lines, and `200` seemed like the sweet spot to me, but obviously it was wrong. I was able to solve your problem by changing this value to `50`.

You can find this change in `1.7.0`, so update the lib and try again.

Also, in order to fix this for good, I exposed a variable for this in the CLI. The default value will be `50` from now on, but you can override it anytime if you want more or less lines per request.

Let me know if this worked for you once you test it.

Also, thank you for the key, you can revoke it now.

**Comment by Andrew-Tierno** [comment]
Hmmm testing it out, I had to crank it down to `5` for it to work consistently on `hi` and `zh`, but when I do that `fr` suddenly becomes problematic! For now I'm going to have a special case for `fr`, but if you have any thoughts on why this may be the case please let me know. I'll keep the key up for now in case you want to test.

This issue may also be worth a comment in your README?

**Comment by while1618** [comment]
I'm really not sure why google response is like this. I'm sending data the same way for all translate apis, but only google is having a problem like this. I just tried it with `fr` and I faced the same problem. It's probably related to the amount of text that is being sent.

Yea, I will definitely update the readme.

Hope that I could help you at least a little with this. For the problematic languages, you can play with `maxLinesPerRequest` or try to use different translate provider for those languages.

**Comment by while1618** [comment]
The issue is now mentioned in the readme. 

Deleted comments were the one related to the api key, I just wanted to hide them if someone reads this, because they are not related to the issue at all.
