### ISSUE TITLE
alphabetical sorting

### ISSUE THREAD

**Issue by szamanr** [while1618/i18n-auto-translation#47]
hello and thanks for the great library!

my source file is alphabetically sorted, but when i add a new string and call the translation script, it gets added to the bottom. is there a way to configure it to preserve the alphabetical sorting?

thanks!

**Comment by while1618** [comment]
Currently, it is not possible. And it will be a bit problematic to do it. The only idea I can think of right now is to add a flag, that if enabled, will just rearrange the file in alphabetical order after the translation is done.

If this is something that is important to you, I can try to implement it in the future. But I'm just curious, why you need that file to be alphabetically sorted?

**Comment by szamanr** [comment]
my original file is automatically sorted, so it would be helpful when reviewing translations to have the same strings be in the same place across files.

in the meantime i'll probably add a sorting step to my build flow with something like [jsonsort](https://www.npmjs.com/package/json-sort-cli).

**Comment by while1618** [comment]
Hi @szamanr,

I just publish a new release `v1.8.0`. 

Now, after you update an existing translation file, library will not just append at the end of the file, but it will compare the original file with the translated one, and it will rearrange keys as in the original file.

With this, if your file is alphabetically sorter, it will remain like that after translation.
