### ISSUE TITLE
Empty Space at the beginning of the string is removed in the response json

### ISSUE THREAD

**Issue by saravna** [while1618/i18n-auto-translation#50]

**Comment by while1618** [comment]
Hi @saravna, yes, this is implemented because of the issue #4. 
Maybe I can add a flag to disable `trim()` method, but that might cause you more problems than just to add spaces where you need them in your translations. Once you change your translations, they won't be overridden by the library

**Comment by while1618** [comment]
This is now possible starting from `v1.10.0`. There is a flag `trim` which is `true` by default. If you want to disable this behavior, just set it to `false`.
