### ISSUE TITLE
Add context to translations

### ISSUE THREAD

**Issue by Telsho** [while1618/i18n-auto-translation#52]
Hi, 

I wanted to know if it would be possible to add a context flag. I know that for deepl there is such parameter.
Let me know if you have already something otherwise you can assign it to me without problem.

**Comment by while1618** [comment]
Hi @Telsho,

Thanks for the suggestion. I just added `context` and `formality` parameters, they both can be used only for deepl api translate. [Deepl Docs](https://developers.deepl.com/docs/api-reference/translate#request-body-descriptions)

New parameters are available from `v1.9.0`
