### ISSUE TITLE
Tagalog (tl) google translation bug

### ISSUE THREAD

**Issue by ruslanruslanruslan** [while1618/i18n-auto-translation#53]
Starting from 1.5.0 version tl language from google-official begin to generate wrong json. For example. I try to translate this:
`{
  "campaigns": "Campaigns",
  "vouchers": "Vouchers"
}
`
But receive this:
`{
  "campaigns": "Mga kampanya\n#___#\nMga voucher"
}`
Version 1.4.2 works ok.
May anybody help me to fix this problem please?

**Comment by while1618** [comment]
Hi @ruslanruslanruslan,

For some reason, when translating Tagalog, the string that is returned from the translate api have wrong delimiter. The returned value is  `#___#` but it should be `#__#`. 

I fixed this in `v1.9.1`
